camera_tracker_node:
  ros__parameters:
    # HSV tuned for blue; adjust as needed
    hsv_lower: [90, 80, 40]
    hsv_upper: [130, 255, 255]
    min_area: 200
    ema_alpha: 0.35
    depth_median_window: 5
    depth_default: 0.8
    depth_scale: 0.001